[[python-logging]]
Python Logging
~~~~~~~~~~~~~~

[[rules-of-thumb]]
Rules of Thumb
^^^^^^^^^^^^^^

* Use Python logging module.
* Always use a per-app logger.
* Use per-module loggers as necessary.
* One logger per file, named "logger"
* Leave logging statements in place
* Use built-in string interpolation
* Scrub out all PII/PHI whenever possible, particular in loglevels >
debug.
* 500 errors on the site should always generate a log message
* Production servers should never run with debug logging enabled.

[[example]]
Example
^^^^^^^

----------------------------------------
import logging
logger = logging.getLogger(__name__)
logger.debug('initialized %s', __name__)
----------------------------------------

[[log-levels]]
Log Levels
^^^^^^^^^^

By default, logging directives should fall into one of the following
categories when they are not specifically called out as being a part of
another class of logs.

[[debug]]
debug
+++++

Information that is only useful while coding or debugging. Debug
information should always be information dense and represent normal
operation.

[[examples]]
Examples:

* progress through a state machine
* progress through a linear computation
* state information relevant to debugging control flow (http request
contents, etc)

[[info]]
info
++++

Information that is useful to track ongoing operation of the system.
Info logs should always represent normal operation.

[[examples-1]]
Examples:

* counter progress through a bulk operation
* user activities
* administrative activities
* instantiation of background tasks

[[warning]]
warning
+++++++

Information that is useful to track exceptional conditions. Warnings
should always represent normal operation in response to errors.

[[examples-2]]
Examples:

* handled exceptions
* unexpected validation failures
* unexpected (but handled) task termination

[[error]]
error
+++++

Information representing recoverable error conditions. Error logs should
be reserved for unhandled application exceptions that should be
recoverable by creating a new request or a simple restart of the
application. Calls to logger.exception() will be logged with at the
"error" level.

[[examples-3]]
Examples:

* failed assertions
* loss of application state
* other unrecoverable errors

[[critical]]
critical
++++++++

Information representing critical failure conditions. Critical logs
should be reserved for errors that represent an unrecoverable error
condition, such as the i or connect to a required database resource.

[[examples-4]]
Examples:

* inability to bind to an ip address
* unavailable database resources
* missing filesystem access permissions or mountpoints

[[access-logging]]
Access Logging
^^^^^^^^^^^^^^

User accesses should be logged using the via the access_logger in the
profile. The benefit of wrapping everything with a function is we have
centralized control of the message formatting and send messages to
alternate locations if necessary.

[[access-logger-example-implementation]]
Access Logger Example Implementation
++++++++++++++++++++++++++++++++++++

-------------------------------------------------------------------------------------
import logging
from services_profile.constants import ACCESS_LOG_PROFILE_UPDATED, ACCESS_LOG_CREATED
_access_logger = logging.getLogger('access')
 
def created(user, req, details):
    _access_logger.info('%s: %s', ACCESS_LOG_CREATED, user)
 
def updated(user, req, details):
    _access_logger.info('%s: %s', ACCESS_LOG_PROFILE_UPDATED, user)
-------------------------------------------------------------------------------------

[[access-logger-usage]]
Access Logger Usage
+++++++++++++++++++

------------------------------------------
from services_profile import access_log
access_log.created(user, None, attributes)
------------------------------------------

[[admin-audit-logging]]
Admin Audit Logging
+++++++++++++++++++

Administrative actions should be logged following the same pattern as
access logs.

[[logging-configuration]]
Logging Configuration
^^^^^^^^^^^^^^^^^^^^^

The logging system is configured via the "LOGGING" parameter in each
project's setting.py. The default settings are meant to be conservative,
but ideal for production performance, and should be adjusted to stay
that way. For the profile service, they look like this:

[source,python]
include::django-logging-example.adoc

For development use, you will likely want more detailed logging.
Conveniently, you can override these settings via local_settings.py if
needed. Some examples are contained in the local_settings.py.example,
such as these:

[source,python]
include::django-logging-example-local.py

[[python-exception-handling]]
Python Exception Handling
~~~~~~~~~~~~~~~~~~~~~~~~~

[[rules-of-thumb-1]]
Rules of Thumb:
^^^^^^^^^^^^^^^

* Never catch raw "Exception".
* Never catch an exception you can't handle – allow them to bubble up.
* Log messages for exceptions you can handle.

[[custom-exceptions]]
Custom Exceptions
^^^^^^^^^^^^^^^^^

Create custom exceptions where appropriate and use them in tests:

--------------------------------------------------
class MyCustomException(Exception):
    pass
 
class MyClass(object):
    def has_errors(self):
        raise MyCustomException('much fail')
     
 
class MyTestCase(TestCase):
    def test_it(self):
        my_class = MyClass()
        with self.assertRaises(MyCustomException):
            my_class.has_errors()
--------------------------------------------------

[[javascript-logging]]
Javascript Logging
~~~~~~~~~~~~~~~~~~

Javascript logging should be as organized and effective as python
logging.
