== GitHub PR-merge-squash Workflow

When using GitHub there are a variety of possible workflows. Each has their
own merits, but for a large, long-running project with a number of committers
it is worth considering taking the extra time to follow a fork, merge-squash
strategy.

The PR, merge-squash strategy works as follows. There are 3 "roles" involved. These
roles may not necessarily filled by different people, but for the sake of clarity each
step is assigned to one of them.

Product Management::
  Product Management tasked with understanding the long term goals of the project and
  measuring progress towards them. These people are also responsible for outlining the work
  to be done and verifying that changes made work as expected.
Maintainers::
  Maintainers are the technical staff responsible for maintaining the repository. They
  are responsible for approving the code and keeping it moving through the pipeline.
Contributor::
  Contributors are the technical staff responsible for implementing features.

=== Steps

.Product Manager
a. If necessary, the project management team creates Milestones and perhaps Issues
   representing the work to be completed.

.Contributor
1. create a branch from the master branch in the wisertogether repository.
2. clone their branch to their local workstation
3. write code, committing it to their branch frequently
4. push their local feature-branch to the wisertogether repository
5. use GitHub's "Compare and Pull Request" feature to open a pull request against
   the master repository
6. update the pull request's description field with an accurate description of the
   change, conforming to the commit message guidelines
    * the first line of the message shoul be 58 char or less and contain the milestone number
    * the 3rd and subsequent lines should contain the text "fixes #xxx" where xxx is the
      github issue(s) that are fixed by this pull request
    * the 3rd and subsequent lines should also contain a detailed description of what the
      code actually "is" and "does".

.Maintainer
1. review the pull request
2. provide in-line feedback as needed

.Contributor
1. respond to the feedback
2. provide updated commits to their branch as needed.

Once the pull request meets the feature requirements, code review, and is otherwise
deemed to be complete, the Maintainer will merge the pullrequest and close the associated
issues and the pull request itself by including `fixes #000` in the pull request.

The maintainer, upon merging the pull request, should also delete the feature branch that the pull request was created from.
